services:
  chronocat:
    image: he0119/chronocat-docker
    tty: true
    container_name: chronocat
    restart: always
    ports:
      - "6080:80"
      - "5901:5901"
      - "16530:16530"
    environment:
      - VNC_PASSWD=password
    volumes:
      - ./Tencent Files:/root/Tencent Files
      - ./BetterUniverse:/wine/drive_c/users/root/AppData/Roaming/BetterUniverse
